export const MOMO_RETURN_CONSTANTS = {
  MOMO_ERROR_MAP: {
    0: 'Giao dịch thành công.',
    10: 'Hệ thống đang được bảo trì. Vui lòng quay lại sau khi bảo trì được hoàn tất.',
    11: 'Truy cập bị từ chối. Cấu hình tài khoản doanh nghiệp không cho phép truy cập.',
    12: 'Phiên bản API không được hỗ trợ cho yêu cầu này. Vui lòng nâng cấp lên phiên bản mới nhất.',
    13: 'Xác thực doanh nghiệp thất bại. Vui lòng kiểm tra thông tin kết nối.',
    20: 'Yêu cầu sai định dạng. Vui lòng kiểm tra định dạng của yêu cầu.',
    21: 'Yêu cầu bị từ chối vì số tiền giao dịch không hợp lệ.',
    22: 'Số tiền giao dịch không hợp lệ.',
    40: 'RequestId bị trùng. Vui lòng thử lại với một requestId khác.',
    41: 'OrderId bị trùng. Vui lòng truy vấn trạng thái hoặc thử lại với orderId khác.',
    42: 'OrderId không hợp lệ hoặc không được tìm thấy.',
    43: 'Yêu cầu bị từ chối vì xung đột trong quá trình xử lý giao dịch.',
    45: 'Trùng ItemId. Vui lòng thử lại với ItemId duy nhất.',
    47: 'Yêu cầu bị từ chối vì thông tin không hợp lệ trong danh sách dữ liệu khả dụng.',
    98: 'QR Code tạo không thành công. Vui lòng thử lại.',
    99: 'Lỗi không xác định. Vui lòng liên hệ MoMo để biết thêm chi tiết.',
    1000: 'Giao dịch đã được khởi tạo, chờ người dùng xác nhận thanh toán.',
    1001: 'Giao dịch thanh toán thất bại do tài khoản người dùng không đủ tiền.',
    1002: 'Giao dịch bị từ chối do nhà phát hành tài khoản thanh toán.',
    1003: 'Giao dịch đã bị hủy.',
    1004: 'Giao dịch thất bại do số tiền thanh toán vượt quá hạn mức.',
    1005: 'Giao dịch thất bại do url hoặc QR code đã hết hạn.',
    1006: 'Giao dịch thất bại do người dùng đã từ chối xác nhận thanh toán.',
    1007: 'Giao dịch bị từ chối vì tài khoản không tồn tại hoặc đang ngưng hoạt động.',
    1017: 'Giao dịch bị hủy bởi đối tác.',
    1026: 'Giao dịch bị hạn chế theo thể lệ chương trình khuyến mãi.',
    1080: 'Giao dịch hoàn tiền thất bại trong quá trình xử lý.',
    1081: 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu có thể đã được hoàn.',
    1088: 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu không được hỗ trợ hoàn tiền.',
    2019: 'Yêu cầu bị từ chối vì orderGroupId không hợp lệ.',
    4001: 'Giao dịch bị từ chối do tài khoản người dùng đang bị hạn chế.',
    4002: 'Giao dịch bị từ chối do tài khoản người dùng chưa được xác thực với C06.',
    4100: 'Giao dịch thất bại do người dùng không đăng nhập thành công.',
    7000: 'Giao dịch đang được xử lý. Vui lòng chờ giao dịch được xử lý hoàn tất.',
    7002: 'Giao dịch đang được xử lý bởi nhà cung cấp loại hình thanh toán.',
    9000: 'Giao dịch đã được xác nhận thành công.',
  },
};
